description "Ceph radosgw (reload all instances)"

start on radosgw-all-reload or ceph-all-reload

task

script
    # someday upstart will let us reload all instances
    # with a wildcard or something similar; see
    # https://bugs.launchpad.net/upstart/+bug/1012938
    # until then,
    killall -1 radosgw
end script
