/var/log/ceph/*.log {
    rotate 7
    daily
    compress
    sharedscripts
    postrotate
        invoke-rc.d ceph reload >/dev/null || service ceph reload >/dev/null
	initctl emit ceph-all-reload >/dev/null
    endscript
    missingok
}
