---
name: "Trigger make check"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}
