---
name: "Trigger make check"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: List changed files
        uses: knu/changed-files@v1.0.0
