---
name: "Trigger make check"
on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$COMMENT_BODY"
        env: 
          COMMENT_BODY: ${{ github.event.comment.body }}

  list-changes:
    runs-on: ubuntu-latest
    needs: debug
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'trigger') }}
    steps:
      - name: List changed files
        uses: knu/changed-files@v1
        with:
          paths: "**"
        id: changed_files

      - name: Echo changed files
        run: "echo changed files: ${{ steps.changed_files.outputs.all }}"

